### PR TITLE
Preparing Repo for ZIO 2.x Upgrade

### PR DESCRIPTION
**Pull request by ASRagab**
## What 

Closes Issue zio/interop-twitter#214

## Notes

Currently using `M6-2` should hopefully be a one-line sbt change when the time comes, and zio 2.0 is GA

### CODE REVIEW

**Review by adamgfraser — APPROVED** [review]
Thank you! 🙏

**Comment by mijicd** [comment]
@ASRagab could you please resolve the (newly introduced) conflicts with `master`? Sorry for that :pray:

**Comment by ASRagab** [comment]
> @ASRagab could you please resolve the (newly introduced) conflicts with `master`? Sorry for that 🙏

@mijicd @adamgfraser conflicts resolved

**Comment by mijicd** [comment]
Merging as soon as the build passes.

**Comment by ASRagab** [comment]
> Merging as soon as the build passes.

I am not really sure what the issue is, but happy to investigate or help out.

**Comment by mijicd** [comment]
I think 2.11. is misbehaving. I noticed that on `master` as well, but I can't reproduce it locally. Anyhow, I rerun the build, let it pass on other environments, and then if you want to dig into 2.11 sure, if not, I'll do it.

**Comment by ASRagab** [comment]
@mijicd Yeah, I'll see if I can reproduce

**Comment by mijicd** [comment]
Thank you!

**Review by mijicd — APPROVED** [review]

**Comment by mijicd** [comment]
This PR should be merged and interop needs to be fixed on both branches as discussed over Discord. Thanks for taking care of this!

**Pull request merged**
